name: Publish Package
on:
  push:
    branch: main
  #   tags:
  #     - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup
        uses: actions/setup-node@v4
        with:
          registry-url: https://npm.pkg.github.com
          scope: 'hoshi4444'
      - name: Install
        run: yarn install
      - name: build
        run: yarn build
      - name: publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
