name: Publish Package
on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        options:
          - --prerelease
          - --patch
          - --minor
        required: true
        description: 'バージョンアップパターン'


jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Git Config
        run: |
          git config --global user.name "${USERNAME}"
          git config --global user.email "${EMAIL}"
        env:
          USERNAME: github-actions[bot]
          EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: setup
        uses: actions/setup-node@v4
        with:
          always-auth: true
          registry-url: https://npm.pkg.github.com
          scope: '@hoshi4444'
      - name: Version Up
        run: |
          yarn version ${{ inputs.version }}
          git push origin HEAD
          git push origin --tags
      - name: Create release
        run: |
          version="$(git describe --tags --abbrev=0)"
          gh create release "${version}" --title "${version}" --generate-token
      - name: Install
        run: yarn install
      - name: build
        run: yarn build
      - name: publish
        run: yarn publish